// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'auxiliarySlot': string;
  'canDrop': string;
  'categoryTab': string;
  'categoryTabs': string;
  'characterSwitcher': string;
  'characterTab': string;
  'classIcon': string;
  'className': string;
  'content': string;
  'deckRows': string;
  'deckStoreHeaders': string;
  'equipmentBucket': string;
  'equipmentRail': string;
  'identity': string;
  'identityText': string;
  'inventoryContainer': string;
  'inventoryDeck': string;
  'isOver': string;
  'power': string;
  'rightAlignedRail': string;
  'selectedCategory': string;
  'selectedCharacter': string;
  'singleCharacterButton': string;
  'singleStore': string;
  'stage': string;
  'subclassSlot': string;
  'title': string;
  'toolbar': string;
}
export const cssExports: CssExports;
export = cssExports;
