// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'selected': string;
  'toggle': string;
  'toggleButton': string;
}
export const cssExports: CssExports;
export = cssExports;
