// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'armorClassIcon': string;
  'emptyEngram': string;
  'emptyGearSlot': string;
  'engrams': string;
  'inlineGroups': string;
  'notEquippable': string;
  'pullItemButton': string;
  'pullItemGridButton': string;
  'subClass': string;
  'vaultGroup': string;
  'weaponGroupingIconWrapper': string;
}
export const cssExports: CssExports;
export = cssExports;
